# -*- coding: utf-8 -*-
"""automation&loops.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l7lESPwfxt89LAxV0YURvdmz2kyBQT7P
"""

TOTAL_SEATS = 350
remaining_seats = TOTAL_SEATS

total_bookings = 0
tickets_sold = 0
rejected_bookings = 0

while True:
    tickets = int(input("Enter number of tickets (0 to exit): "))

    if tickets == 0:
        break

    if tickets < 1 or tickets > 15:
        print("BOOKING REJECTED - Invalid ticket count")
        rejected_bookings += 1
        continue

    if tickets > remaining_seats:
        print("BOOKING REJECTED - Not enough seats")
        rejected_bookings += 1
        continue

    valid_booking = True

    # for loop must be indented
    for i in range(tickets):
        age = int(input(f"Enter age of person {i+1}: "))

        if age < 12:
            valid_booking = False

    # only one check needed
    if not valid_booking:
        print("BOOKING REJECTED - Age restriction")
        rejected_bookings += 1
        continue

    print(f"BOOKING CONFIRMED - {tickets} tickets")
    total_bookings += 1
    tickets_sold += tickets
    remaining_seats -= tickets

    if remaining_seats == 0:
        print("Theatre is now FULL")
        break

print("\n--- FINAL REPORT ---")
print(f"Total Bookings: {total_bookings}")
print(f"Total Tickets Sold: {tickets_sold}")
print(f"Rejected Bookings: {rejected_bookings}")
print(f"Remaining Seats: {remaining_seats}")